Mayhem Heroes Integration
mayhemheroes/HighFive pull request #1
Opened 2023-01-28 00:13 UTC by capuanob

Initial PR

2023-02-02 16:53 UTC, xansec requested changes
Please make the requested changes.

2023-02-02 16:53 UTC, xansec commented on mayhem/FuzzedDataProvider.h
> +//===- FuzzedDataProvider.h - Utility header for fuzz targets ---*- C++ -* ===//
Please don't include FDP.

2023-02-03 01:43 UTC, capuanob commented on mayhem/FuzzedDataProvider.h
> +//===- FuzzedDataProvider.h - Utility header for fuzz targets ---*- C++ -* ===//
@xansec Done!

2023-02-09 13:54 UTC, xansec approved these changes
LGTM!

2023-02-09 13:54 UTC, merged